name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Linting
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config=.flake8 app/

    # Run tests
    #- name: Run tests
    #  run: |
    #    pip install pytest
    #    pytest tests/

    
  #deploy:
    #needs: build-and-test
    #runs-on: ubuntu-latest

    #steps:
    # Checkout the code
    #- name: Checkout code
    #  uses: actions/checkout@v3

    # Deploy w/ AWS
    #- name: Deploy to environment
    #  run: |
    #    docker build -t recipe-management:latest .
    #    docker run -d -p 8000:8000 recipe-management:latest
    
    