name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # set the path
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV

    # Debugging: Print working directory and contents
    - name: Debug working directory
      run: |
        echo "Working Directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        ls -R

    # Linting
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config=.flake8 app/

    # Run tests
    - name: Run tests
      run: |
        pip install pytest
        pip install httpx
        echo "Running pytest with PYTHONPATH: $(pwd)/app"
        pytest tests/

    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install -r requirements.txt
          pkill -f uvicorn || true
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
    
    