name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # set the path
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV

    # Linting
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config=.flake8 app/

    # Run tests
    - name: Run tests
      run: |
        pip install pytest
        pip install httpx
        echo "Running pytest with PYTHONPATH: $(pwd)/app"
        pytest tests/

    #set file permissions
    - name: Set permissions for the private key
      run: |
        chmod 600 app/jigglypuff.pem

    #deploy using learner lab
    - name: Deploy to Learner Lab EC2
      run: |
          ssh -t -o StrictHostKeyChecking=no -i app/jigglypuff.pem ec2-user@34.228.116.77 << EOF    
            sudo yum update -y
            sudo yum install -y git python3 python3-pip
            pip3 install uvicorn

            cd /home/ec2-user
            if [ ! -d "/home/ec2-user/4153-recipe-management" ]; then
              git clone https://github.com/src1026/4153-recipe-management.git 
            else
              cd /home/ec2-user/4153-recipe-management
              git pull origin main
            fi 
            ls
            cd /home/ec2-user/4153-recipe-management
            git pull origin main
            
            pip3 install -r requirements.txt
            pkill -f uvicorn || true
            echo "Starting uvicorn server"
            nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
            sleep 5
            if pgrep -f uvicorn; then
                echo "Uvicorn started successfully"
            else
                echo "Failed to start uvicorn"
                cat uvicorn.log
            fi
          EOF
    
    #- name: Deploy to EC2 
    #  uses: appleboy/ssh-action@v0.1.7
    #  with:
    #    host: ${{ secrets.EC2_HOST }}
    #    username: ${{ secrets.EC2_USERNAME }}
    #    key: ${{ secrets.EC2_PRIVATE_KEY }}
    #    port: 22
    #    script: |
    #      sudo yum update -y
    #      sudo yum install -y git python3 python3-pip
    #      pip3 install uvicorn
    #      pip3 install -r requirements.txt
    #      pkill -f uvicorn || true
    #      timeout 5m nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
    
    